chore: improvements

diff --git a/.github/workflows/foundry.yaml b/.github/workflows/foundry.yaml
--- a/.github/workflows/foundry.yaml
+++ b/.github/workflows/foundry.yaml
@@ -1,4 +1,4 @@
-name: foundry
+name: Foundry CI
 
 on:
   pull_request:
@@ -8,8 +8,8 @@ on:
     branches:
       - develop
 
-# env:
-#   NO_COLOR: 1
+env:
+  NO_COLOR: 1
 
 defaults:
   run:
@@ -51,12 +51,23 @@ jobs:
         continue-on-error: true
         run: forge test -vvv 2>&1 | tee test.log
 
-      - uses: actions/github-script@v7
+      - uses: actions/github-script@v8
         if: github.event_name == 'pull_request'
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            // Prepare format of the comment
+            // 1. Retrieve existing bot comments for the PR
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+            })
+            const botComment = comments.find(comment => {
+              return comment.user.id === 41898282 && comment.body.includes(`# Configuration 📍\`${process.env.WORKING_DIR}\``)
+            })
+
+
+            // 2. Prepare format of the comment
             const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
             const run_link = '<a href="' + run_url + '">Actions</a>.'
             const fs = require('fs')
@@ -90,16 +101,30 @@ jobs:
             \`\`\`
 
             </details>
+
             *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
 
-            // Create a comment
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+            // 3. If we have a comment, update it, otherwise create a new one
+            if (botComment) {
+              github.rest.issues.updateComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: botComment.id,
+                body: output
+              })
+            } else {
+              github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: output
+              })
+            }
 
       - name: Fail the ci if any step fails
-        if: failure() || steps.lint.outputs.stdout != ''
-        run: exit 1
+        run: |-
+          lint_file=$(cat lint.log)
+          if [[ "${{ steps.fmt.outcome }}" == "failure" || "${lint_file}" != "" || "${{ steps.test.outcome }}" == "failure" ]]; then
+            echo "Lint failed"
+            exit 1
+          fi
